In [4]:
import pandas as pd
import numpy as np

%matplotlib inline
# activate plot theme
import qeds
qeds.themes.mpl_style();

In [84]:
url = "https://datascience.quantecon.org/assets/data/bball.csv"
bball = pd.read_csv(url)

bball_long = bball.melt(id_vars=["Year", "Player", "Team", "TeamName"])
bball_wide = bball_long.pivot_table(
    index="Year",
    columns=["Player", "variable", "Team"],
    values="value"
)

bball

   Year  Player Team  TeamName  Games   Pts  Assist  Rebound
0  2015   Curry  GSW  Warriors     79  30.1     6.7      5.4
1  2016   Curry  GSW  Warriors     79  25.3     6.6      4.5
2  2017   Curry  GSW  Warriors     51  26.4     6.1      5.1
3  2015  Durant  OKC   Thunder     72  28.2     5.0      8.2
4  2016  Durant  GSW  Warriors     62  25.1     4.8      8.3
5  2017  Durant  GSW  Warriors     68  26.4     5.4      6.8
6  2015   Ibaka  OKC   Thunder     78  12.6     0.8      6.8
7  2016   Ibaka  ORL     Magic     56  15.1     1.1      6.8
8  2016   Ibaka  TOR   Raptors     23  14.2     0.7      6.8

## Exercises


<a id='exerciselist-0'></a>
**Exercise 1**

(*Warning*: This one is challenging):

Recall the `bball_wide` DataFrame from above (repeated below to jog
your memory).

In this task, you will start from `ball` and re-recreate `bball_wide`
by combining the operations we just learned about.

There are many ways to do this, so be creative.

Our solution used `set_index`, `T`, `stack`, and `unstack` in
that order.

Here are a few hints:

- Think about what columns you will need to call `set_index` on so
  that their data ends up as labels (either in index or columns).  
- Leave other columns (e.g. the actual game stats) as actual columns so
  their data can stay data during your reshaping.  


Don't spend too much time on this... if you get stuck, open up **this**
markdown cell, and you will see our answer hidden.

**Hint**: You might need to add `.sort_index(axis=1)` after you are
finished to get the columns in the same order.

**Hint**: You may not end up with a `variable` header on the second
level of column labels. This is ok.

<div style="display: none;">

`bball.drop("TeamName", axis=1).set_index(["Year", "Player", "Team"]).stack().unstack(level=[1, 3, 2]).sort_index(axis=1)`

</div>

In [62]:
'''
First drop TeamName from table since it is not shown in the final wide table
Add Year, Player and Team to Index since we only want player stats to be stacked into a series
Stack game stats into a PD series
In order to reobtain the column labels in the right order, we need to "pop" or unstack in a certain order

By indices:
0 = Year
1 = Player
2 = Team
3 = variable (player stats)

The order of bball_wide is Player, variable, then Team for column labels, so the unstack order must be (by index) 
a list [1,3,2] to create all the column labels we need, keeping year as the index of the dataframe

Finally sort the data to obtain bball_wide
'''
bball.drop("TeamName", axis=1).set_index(["Year", "Player", "Team"]).stack().unstack(level=[1,3,2]).sort_index(axis=1)

Player  Curry                     Durant                               ...  \
       Assist Games   Pts Rebound Assist      Games         Pts        ...
Team      GSW   GSW   GSW     GSW    GSW  OKC   GSW   OKC   GSW   OKC  ...
Year                                                                   ...
2015      6.7  79.0  30.1     5.4    NaN  5.0   NaN  72.0   NaN  28.2  ...
2016      6.6  79.0  25.3     4.5    4.8  NaN  62.0   NaN  25.1   NaN  ...
2017      6.1  51.0  26.4     5.1    5.4  NaN  68.0   NaN  26.4   NaN  ...

Player  Ibaka
       Assist Games               Pts             Rebound
Team      TOR   OKC   ORL   TOR   OKC   ORL   TOR     OKC  ORL  TOR
Year
2015      NaN  78.0   NaN   NaN  12.6   NaN   NaN     6.8  NaN  NaN
2016      0.7   NaN  56.0  23.0   NaN  15.1  14.2     NaN  6.8  6.8
2017      NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN  NaN  NaN

[3 rows x 24 columns]

In [36]:
bball_wide

Player    Curry                     Durant                               ...  \
variable Assist Games   Pts Rebound Assist      Games         Pts        ...
Team        GSW   GSW   GSW     GSW    GSW  OKC   GSW   OKC   GSW   OKC  ...
Year                                                                     ...
2015        6.7  79.0  30.1     5.4    NaN  5.0   NaN  72.0   NaN  28.2  ...
2016        6.6  79.0  25.3     4.5    4.8  NaN  62.0   NaN  25.1   NaN  ...
2017        6.1  51.0  26.4     5.1    5.4  NaN  68.0   NaN  26.4   NaN  ...

Player    Ibaka
variable Assist Games               Pts             Rebound
Team        TOR   OKC   ORL   TOR   OKC   ORL   TOR     OKC  ORL  TOR
Year
2015        NaN  78.0   NaN   NaN  12.6   NaN   NaN     6.8  NaN  NaN
2016        0.7   NaN  56.0  23.0   NaN  15.1  14.2     NaN  6.8  6.8
2017        NaN   NaN   NaN   NaN   NaN   NaN   NaN     NaN  NaN  NaN

[3 rows x 24 columns]

([*back to text*](https://datascience.quantecon.org/#exercise-0))

**Exercise 2**

- What do you think would happen if we wrote `bball.melt(id_vars=["Year", "Player"])`
  rather than `bball.melt(id_vars=["Year", "Player", "Team", "TeamName"])`?
  Were you right? Write your thoughts.  
  
  **When using melt, id_vars indicate columns that should not be melted, index labels included.
  For the first case, only Year, Player, a variable column, and a corresponding value column
  holding all other "tidied" data would remain after a melt. For the second case, only the 
  player game statistics would be melted including Games, Pts, Rebounds, and Assists in the variable column
  alongside the corresponding value column.**
  
- Read the documentation and focus on the argument `value_vars`. How
  does `bball.melt(id_vars=["Year", "Player"], value_vars=["Pts", "Rebound"])`
  differ from `bball.melt(id_vars=["Year", "Player"])`?
  
  **Using keyword argument value_vars designates specific column data to use for melted or "tidied" data.
  For both cases, Year and Player have their own respective columns, but for the first case, only the Pts and
  Rebound columns are melted into the variables column with corresponding values, and the rest are removed.
  For the second case, all column data besides Year and Player are melted into the variable column with corresponding
  value column.**
  
- Consider the differences between `bball.stack` and `bball.melt`.
  Is there a way to make them generate the same output?
  (Hint: you might need to use both `stack` and another method from
  above)? Write your thoughts.  

  **By using the set_index method on desired columns, we can preserve columns we don't wish to "melt" when
  invoking the stack command. If we still wish to utilize as a dataframe and not a multi-index series, however,
  we must reset the index afterwards**
  
([*back to text*](https://datascience.quantecon.org/#exercise-1))

**Exercise 3**

- First, take a breath... That was a lot to take in.  
- Can you think of a reason to ever use `pivot` rather than
  `pivot_table`? Write your thoughts.  
- Create a pivot table with column `Player` as the index, `TeamName` as the
  columns, and `[Rebound, Assist]` as the values. What happens when you use
  `aggfunc=[np.max, np.min, len]`? Describe how Python produced
  each of the values in the resultant pivot table.  

  **If a dataframe contains data that does not make sense to have aggregated, then pivot would be preferable to
  pivot_table. However since pivot_table is a generalization of pivot, it is a more robust option in almost
  any other situation.
  
  When using multiple aggregate functions, pandas will layer the results, producing a single table with labels
  to denote the results of different aggregate functions. If there are multiple values for a given column, index
  value, np.max will take the highest of values, np.min will take the lowest of the values, and len denotes
  how many dpulicates values there were. Note that pivot alone would produce an error when trying to work with
  duplicates column, index values when in long or wide format**

([*back to text*](https://datascience.quantecon.org/#exercise-2))

In [78]:
#Exercise 2

#Verify assumptions in 2.1, remove .head() to see full results
print("Table 2.1.1")
print(bball.melt(id_vars=["Year", "Player"]).head())
print("Table 2.1.2")
print(bball.melt(id_vars=["Year", "Player", "Team", "TeamName"]).head())

Table 2.1.1
   Year  Player variable value
0  2015   Curry     Team   GSW
1  2016   Curry     Team   GSW
2  2017   Curry     Team   GSW
3  2015  Durant     Team   OKC
4  2016  Durant     Team   GSW
Table 2.1.2
   Year  Player Team  TeamName variable  value
0  2015   Curry  GSW  Warriors    Games   79.0
1  2016   Curry  GSW  Warriors    Games   79.0
2  2017   Curry  GSW  Warriors    Games   51.0
3  2015  Durant  OKC   Thunder    Games   72.0
4  2016  Durant  GSW  Warriors    Games   62.0

In [77]:
#Verify behavior of kwarg value_vars for 2.2
print("Table 2.2.1")
print(bball.melt(id_vars=["Year", "Player"], value_vars=["Pts", "Rebound"]).head())
print("Table 2.2.2")
print(bball.melt(id_vars=["Year", "Player"]).head())

Table 2.2.1
   Year  Player variable  value
0  2015   Curry      Pts   30.1
1  2016   Curry      Pts   25.3
2  2017   Curry      Pts   26.4
3  2015  Durant      Pts   28.2
4  2016  Durant      Pts   25.1
Table 2.2.2
   Year  Player variable value
0  2015   Curry     Team   GSW
1  2016   Curry     Team   GSW
2  2017   Curry     Team   GSW
3  2015  Durant     Team   OKC
4  2016  Durant     Team   GSW

In [101]:
#Verify stack vs melt behavior
print(bball.set_index(["Year", "Player"]).stack().reset_index().head())
print("------")
print(bball.melt(id_vars=["Year", "Player"]).head())

   Year Player   level_2         0
0  2015  Curry      Team       GSW
1  2015  Curry  TeamName  Warriors
2  2015  Curry     Games        79
3  2015  Curry       Pts      30.1
4  2015  Curry    Assist       6.7
------
   Year  Player variable value
0  2015   Curry     Team   GSW
1  2016   Curry     Team   GSW
2  2017   Curry     Team   GSW
3  2015  Durant     Team   OKC
4  2016  Durant     Team   GSW

In [111]:
#Exercise 3
bball.pivot_table(index="Player", columns="TeamName", values=["Rebound", "Assist"], aggfunc=[np.max, np.min, len]).T

Player                 Curry  Durant  Ibaka
             TeamName
amax Assist  Magic       NaN     NaN    1.1
             Raptors     NaN     NaN    0.7
             Thunder     NaN     5.0    0.8
             Warriors    6.7     5.4    NaN
     Rebound Magic       NaN     NaN    6.8
             Raptors     NaN     NaN    6.8
             Thunder     NaN     8.2    6.8
             Warriors    5.4     8.3    NaN
amin Assist  Magic       NaN     NaN    1.1
             Raptors     NaN     NaN    0.7
             Thunder     NaN     5.0    0.8
             Warriors    6.1     4.8    NaN
     Rebound Magic       NaN     NaN    6.8
             Raptors     NaN     NaN    6.8
             Thunder     NaN     8.2    6.8
             Warriors    4.5     6.8    NaN
len  Assist  Magic       NaN     NaN    1.0
             Raptors     NaN     NaN    1.0
             Thunder     NaN     1.0    1.0
             Warriors    3.0     2.0    NaN
     Rebound Magic       NaN     NaN    1.0
             Raptors     NaN     NaN    1.0
             Thunder     NaN     1.0    1.0
             Warriors    3.0     2.0    NaN